name: surveyor
description: Tools for surveying Dart sources
version: 0.0.1
homepage: https://github.com/pq/surveyor

# Not intended for publishing.
publish_to: none

environment:
  sdk: '>=2.2.2 <3.0.0'

dependencies:
  analyzer: ^0.39.1
  cli_util: ^0.1.3
  http: ^0.12.0
  # required by example/lint_surveyor
  # linter:  ^0.1.100
  pub_semver: ^1.0.0
  tuple: ^1.0.0

#dependency_overrides:
#  corpus:
#    path: ../corpus

dev_dependencies:
  pedantic: ^1.0.0
